### ISSUE TITLE
GUI下输入路径时后一个双引号不显示

### ISSUE THREAD

**Issue by ikeepo** [dolphindb/DolphinDB#14]
csvpath = "F:\data\candle_201801.csv
最后这个位置实际上是有"的，但是显示不出来。
csvpath = "F:\data\candle_201801.csv\"
如果结尾出现\，就会显示出"

**Comment by windancer79** [comment]
路径需要用 \\ 
"F:\\data\\candle_201801.csv"
或者用反斜杠 
"F:/data/candle_201801.csv"

**Comment by ikeepo** [comment]
明白了
